version: '3'
services:
#mssql docker
  sportski-centar-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Express
    ports:
      - 1401:1433
    networks:
      - sportskiCentarNet

  sportski-centar:
    restart: unless-stopped
    build:
      context: .
    environment:    
      - ConnectionStrings:DefaultConnection=Server=sportski-centar-sql,1433;Database=140168;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 5010:5010
    networks:
      - sportskiCentarNet
    links:
      - sportski-centar-sql
    depends_on:
      - sportski-centar-sql
      
networks:
  sportskiCentarNet:
    driver: bridge   